root: true

env:
  es6: true
  shared-node-browser: true

extends:
  - eslint:recommended
  - plugin:import/recommended
  - prettier

globals:
  global: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2018

plugins:
  - import
  - node
  - prettier

rules:
  import/order: error
  import/unambiguous: error
  no-restricted-syntax:
    - error
    - BindExpression
    - ClassProperty
    - Decorator
    - DoExpression
    - ExportDefaultSpecifier
    - ExportNamespaceSpecifier
    - TypeAnnotation
    - JSXElement
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5

settings:
  import/extensions: ['.mjs', '.js']

overrides:
  - files: ['**/*.mjs']
    parser: espree
    parserOptions:
      ecmaFeatures:
        experimentalObjectRestSpread: false
    plugins:
      - node
    rules:
      no-console: off
      node/no-unsupported-features:
        - error
        - ignores:
            - modules
  - files: ['demo/**/*.js']
    env:
      browser: true
    settings:
      import/resolver: webpack
  - files: ['packages/*/test/**/*.js']
    env:
      mocha: true
    globals:
      assert: true
